name = "your-project-name"
compatibility_date = "2025-07-14"
pages_build_output_dir = "./dist"

# Pages でサポートされている設定のみを使用
[env.production]
# 必要に応じて環境変数を設定
# MY_VARIABLE = "production-value"

[env.preview]
# MY_VARIABLE = "preview-value"

